# Generated by Django 3.0.11 on 2021-02-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20210217_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.Location')),
                ('trip', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trips.Destination'),
        ),
    ]
